### PR TITLE
Chore: Improved nav buttons

### LINKED ISSUE #34: Improve Sign-In and Sign-Up Button
I'd like to improve the sign-in and sign-up buttons in the navigation bar, and as we reduce the width of the viewport, the width of the buttons similarly decreases.

Screenshot 2023-10-13 002723

### PR DESCRIPTION
**Pull request by Mayank-Sharma17**
Improved the alignment of the buttons in the navigation bar, added a hover effect to the buttons to match the design of the website, and previously, when users switched to the mobile view, the buttons were turned into circular buttons.

### Screenshots
Screenshot 2023-10-14 131435

mobile view
Screenshot 2023-10-14 131418

fix #34

### CODE REVIEW

**Comment by Yana-Gupta** [comment]
@Mayank-Sharma17 Please increase the size of the buttons.

**Comment by Mayank-Sharma17** [comment]
ok

**Comment by Mayank-Sharma17** [comment]
@Yana-Gupta done, increased buttons size by 5px.

Screenshot 2023-10-14 204925

**Comment by Yana-Gupta** [comment]
Add some space in between the buttons and margin in top and bottom, on smaller device please check once again the buttons are becoming completely rounded.. fix all those bugs

Also if possible avoid rounded buttons and work on making previous rectangle design responsive... cuz as per I looked previous design my much better than rounded buttons

So try making previous button responsive.

**Comment by Mayank-Sharma17** [comment]
@Yana-Gupta If you want rectangular buttons, I will make them responsive and update you later, previously there is no space between buttons I have added 10px space between them do you want more space? (please tell me in px).

And the buttons are responsive for mobile views and laptop screens, but not for tablets because there is a media query for max-width 700 in 'index.scss', thus we need to add another media query for tablets, can I do that?

Screenshot 2023-10-14 213146

Screenshot 2023-10-14 220036

**Comment by Yana-Gupta** [comment]
Please don't add any space in between the buttons

**Comment by Mayank-Sharma17** [comment]
> Please don't add any space in between the buttons

@Yana-Gupta Done, removed the space between buttons, added margin top and bottom by 12px, changed the max-width to 960px now the buttons are also responsive for the tablets.
Let me know if any changes required.

https://github.com/Yana-Gupta/real-estate-frontend/assets/113251342/9e751753-5e1a-49e8-80d4-2b6c534b52fb

**Comment by Yana-Gupta** [comment]
Please only improve it's responsiveness.. don't make unwanted changes with the height and width of button.

The ui doesn't look better now.. 

Fix all the unwanted changes..

**Comment by Mayank-Sharma17** [comment]
@Yana-Gupta I apologize for any unintended changes to the height and width of the buttons that affected the UI. I removed the margin and padding from the buttons and restored the height to 80px, as it was previously.

**Review by Yana-Gupta — APPROVED** [review]

**Comment by Yana-Gupta** [comment]
Thanks

**Pull request merged**
