### PR TITLE
Feature/issue 16

### LINKED ISSUE #16: Improve the load time of image in home page
Ensure to decrease the rendering time of the image, as it looks unresponsive 

image

### PR DESCRIPTION
**Pull request by theDevSoham**
This PR fixes #16 

## So here I experimented 3 ideas:

* 1 Firstly I removed the ```background: url``` from css and used a separate ```img``` tag. This is because putting the image in css gives absolutely no freedom to perform any action on the same using js.

* 2 Then, I tried converting the image to base64 which is a bad idea considering it's a hero section image so it loads first. Also memoized it. The load time increased instead of decreasing. Later found out base64 images take more bandwidth.

* 3. Finally, I moved the assets directory to public. This is because the static assets are NOT supposed to be put in src. For eg ```index.html``` is in public as it's the static file. Next, I converted the jpg to webp format and compressed it, and preloaded it using the ```link``` tag in the static ```index.html``` file itself. Webp is a next gen extension for rendering images in browser, and further compressing it made the size go below half of it's original size (original: 358kB approx now 131kB approx). Preloading loads the image before it loads any other content making the image and other content visible at the same time.

### Points to note:

1. I'm using Ubuntu and firefox so the compilation is blazing fast on my end. The above observation I made are purely from Network metrics.

2. I haven't removed the ```assets``` dir in ```src``` as there's no way to know where the images from ```src``` is  used other than going through the code minutely. So as of now the assets are there even if that should be removed immediately if you're using static assets (just a suggestion)

### Apart from this please let me know if you find any thing unexpected or faulty from this PR. Will resolve it asap. Thanks for the patience

### CODE REVIEW

**Review by Yana-Gupta — APPROVED** [review]

**Comment by Yana-Gupta** [comment]
Thanks @theDevSoham, but why did you changed these image 

image

**Comment by theDevSoham** [comment]
Hey @Yana-Gupta , apologies I absolutely overlooked this. Actually these are not changed images; the image styling for hero section is affecting this. I've pushed a fix for this issue just now in the same branch. The PR should be updated with the new commit shortly

**Review by Yana-Gupta — APPROVED** [review]

**Comment by Yana-Gupta** [comment]
Thanks @theDevSoham for detailed explanation and for your efforts also that you have put into image optimisation in hero section.

**Comment by Yana-Gupta** [comment]
It's is not required to make a new pull request.. if you push changes in
same branch.. it automatically gets updated.

**Pull request merged**
