### PR TITLE
FIXES ISSUE #17

### PR DESCRIPTION
**Pull request by veerendra19codes**
FIXES ISSUE #17
Improved the design by adding hover effects to the navigation links.🥳

**Screenshots/Recordings**
*before-fullscreen*

https://github.com/Yana-Gupta/real-estate-frontend/assets/113845853/52b3134a-c6e9-406f-bd57-2189793bbe4e

*before-responsive*

https://github.com/Yana-Gupta/real-estate-frontend/assets/113845853/72fc52e4-855d-433c-95df-80df5a913b33

*after-fullscreen*

https://github.com/Yana-Gupta/real-estate-frontend/assets/113845853/a865a218-b770-4cee-a346-6c852b33d753

*after-responsive*

https://github.com/Yana-Gupta/real-estate-frontend/assets/113845853/a7a165e0-5747-4224-94bf-eb591307bf8a

Please review my PR .Hope it helps.✌️😊🥳
(PS: that white spaces in videos are bcoz i edited some pauses,cropped in canva)

### CODE REVIEW

**Comment by Yana-Gupta** [comment]
@veerendra19codes these should work as a link not as button, remove hover effect 

As you can see earlier on small screen the on hover effect there is inconsistent size of button. Just fix that bug not anything else.

**Comment by Yana-Gupta** [comment]
[Screencast from 15-10-23 09:39:46 PM IST.webm](https://github.com/Yana-Gupta/real-estate-frontend/assets/103108630/fb268fcb-6366-4207-b6cb-1c8cabb6c76a)


For your reference.

**Comment by veerendra19codes** [comment]
Plz advice what i can do ,add underline when hovered?

**Review by veerendra19codes — COMMENTED** [review]
please review this changes.Now the nav links looks like link when hovered.
and also the size of overall navbar is shortened to avoid the blank space below earlier

**Screenshots*
*now*
link

If not satisfied ,plz specify exactly what you want, I really want to help.Thank you

**Comment by Yana-Gupta** [comment]
Please don't make any extra change just fix that unresponsive effect when hovered. and remove all these changes you have done.
If you want to beautify it there are several ways you can do, just search about them. Now I really don't like any of the change you have made.

One possible thing you can do is that there is mistake in nav menu while hovering, you can fix it. I have provided you the video for that. 

Thanks

**Comment by veerendra19codes** [comment]
I thought underlined effect when hovered looked good and that effect/inconsistent effect in your video is appearing when you clicking on it i guess,and on my device i m really not getting that issue.Sorry for not helping ,i tried my best .you can still merge it so that i could get a contribution in hacktoberfest,And open a new issue with that video of yours specifying the issue in more detail .😅😅😅

**Comment by veerendra19codes** [comment]
Do anything just don't report it as a spam .I really tried 🙏😭😅

**Pull request closed without merging**
